// UI copy for the integrated (live) mode. Merged into src/i18n.mjs. Server clinical texts are NOT
// translated here (they arrive in Spanish and are shown as they come).
export const liveMessages = {
  en: {
    modeIntegrated: 'Integrated mode (demo server)', modeDemo: 'Demonstration mode (no server)',
    modeCurrent: 'Current mode: {mode}', useDemoMode: 'Use demonstration mode (no server)', useIntegratedMode: 'Back to integrated mode',
    modeChecking: 'Checking the server…', modeUnavailable: 'We could not reach the server. No example data is shown in its place.',
    modeRetry: 'Try the server again',
    liveNotice: 'Synthetic data from the demo Medplum server. Not real patients.',
    liveConnected: 'Integrated mode: data and permissions come from the server.',
    liveEntry: 'Each account signs in to the demo server with its demonstration credentials.',
    livePermissionNote: 'Permissions come from the server (auth/me); locks are enforced there too.',
    liveContextLoading: 'Signing in to the server…',
    liveContextError: 'We could not open this context on the server. Choose an account to retry.',
    liveThrottled: 'The server limits sign-ins (5 per minute). Wait a minute and try again.',
    liveUnavailable: 'The server is not responding. No example data is shown in its place.',
    liveNotConfigured: 'This demonstration account is not configured in this build.',
    liveRoleMissing: 'The server does not offer this context for this account.',
    visitDischarged: 'Discharged',
    liveSource: 'Demo server',
    dischargeTitle: 'Discharge instructions', dischargeLoading: 'Loading discharge instructions…', dischargeError: 'Discharge instructions could not be loaded from the server.',
    dischargePrivate: 'Discharge instructions are private for this account.', dischargeEmpty: 'There are no discharge instructions yet.',
    dischargeAlarms: 'Return to the emergency room if:', dischargePrescriptions: 'Medicines to take', dischargePrescriptionsPrivate: 'Prescriptions are private for this account.',
    dischargeAppointments: 'Follow-up appointment',
    familyLoading: 'Loading family access…', familyError: 'Family access could not be loaded from the server.',
    familyEmpty: 'No family members are linked.', familyShares: 'Shares with {name} ({relationship})',
    familySaving: 'Saving…', familySaveError: 'Could not save. Nothing changed.',
    familyToggle: '{category}: {state}', familyOn: 'shared', familyOff: 'not shared',
    familyDelegateIntro: 'What this account can see of {name}, as granted on the server:',
    category_visita: 'Emergency status', category_medicinas: 'Medicines', category_instrucciones: 'Discharge instructions and appointment', category_estudios: 'Studies and results',
    familyAllowed: 'allowed', familyLocked: 'locked',
    familyShortcutLive: 'Who sees what of this record, from the server.',
  },
  es: {
    modeIntegrated: 'Modo integrado (servidor de demostración)', modeDemo: 'Modo demostración (sin servidor)',
    modeCurrent: 'Modo actual: {mode}', useDemoMode: 'Usar modo demostración (sin servidor)', useIntegratedMode: 'Volver al modo integrado',
    modeChecking: 'Comprobando el servidor…', modeUnavailable: 'No pudimos conectar con el servidor. No se muestran datos de ejemplo en su lugar.',
    modeRetry: 'Probar el servidor otra vez',
    liveNotice: 'Datos sintéticos del servidor Medplum de demostración. No son pacientes reales.',
    liveConnected: 'Modo integrado: los datos y permisos vienen del servidor.',
    liveEntry: 'Cada cuenta inicia sesión en el servidor de demostración con sus credenciales de demo.',
    livePermissionNote: 'Los permisos vienen del servidor (auth/me); los candados también se aplican allí.',
    liveContextLoading: 'Iniciando sesión en el servidor…',
    liveContextError: 'No pudimos abrir este contexto en el servidor. Elija una cuenta para reintentar.',
    liveThrottled: 'El servidor limita los inicios de sesión (5 por minuto). Espere un minuto y vuelva a intentar.',
    liveUnavailable: 'El servidor no responde. No se muestran datos de ejemplo en su lugar.',
    liveNotConfigured: 'Esta cuenta de demostración no está configurada en esta versión.',
    liveRoleMissing: 'El servidor no ofrece este contexto para esta cuenta.',
    visitDischarged: 'De alta',
    liveSource: 'Servidor de demostración',
    dischargeTitle: 'Instrucciones del alta', dischargeLoading: 'Cargando instrucciones del alta…', dischargeError: 'No pudimos cargar las instrucciones del alta desde el servidor.',
    dischargePrivate: 'Las instrucciones del alta son privadas para esta cuenta.', dischargeEmpty: 'Todavía no hay instrucciones del alta.',
    dischargeAlarms: 'Vuelva a Emergencias si:', dischargePrescriptions: 'Medicinas para tomar', dischargePrescriptionsPrivate: 'Las recetas son privadas para esta cuenta.',
    dischargeAppointments: 'Cita de seguimiento',
    familyLoading: 'Cargando acceso de familia…', familyError: 'No pudimos cargar el acceso de familia desde el servidor.',
    familyEmpty: 'No hay familiares vinculados.', familyShares: 'Comparte con {name} ({relationship})',
    familySaving: 'Guardando…', familySaveError: 'No se pudo guardar. No cambió nada.',
    familyToggle: '{category}: {state}', familyOn: 'compartido', familyOff: 'no compartido',
    familyDelegateIntro: 'Lo que esta cuenta puede ver de {name}, según el servidor:',
    category_visita: 'Estado en Emergencias', category_medicinas: 'Medicinas', category_instrucciones: 'Instrucciones del alta y cita', category_estudios: 'Estudios y resultados',
    familyAllowed: 'permitido', familyLocked: 'con candado',
    familyShortcutLive: 'Quién ve qué de este récord, según el servidor.',
  },
};
