const copy = {
  es: {
    resultsAvailable: 'Resultados disponibles',
    portalTagline: 'Su portal, su récord médico.',
    demo: 'Demostración · datos ficticios',
    resultsIntro: 'Sus resultados del hospital, en sus manos.',
    searchFilters: 'Buscar o filtrar',
    viewReport: 'Ver informe',
    viewReportLabel: 'Ver informe: {name}',
    closeReport: 'Cerrar informe',
    closeReportLabel: 'Cerrar informe: {name}',
    aboutReport: 'Sobre este informe de ejemplo',
    demoControls: 'Controles de demostración',
    demoControlsBody: 'Cambie la vista del ejemplo. No inicia sesión ni modifica permisos reales.',
    demoDetails: 'Acerca de esta demostración',
    demoBody: 'Este prototipo no está conectado a hospitales ni a PRHIE. Las cuentas, los permisos y los cambios son ejemplos locales; no se guardan al recargar.',
    welcome: 'Su portal,\nsu récord médico.',
    welcomeBody: 'Su visita, sus resultados y su cuidado, en un espacio pensado para usted y su familia.',
    entryTitle: 'Explore el portal',
    entryBody: 'Seleccione una cuenta de demostración para comenzar.',
    patientPortal: 'PORTAL DEL PACIENTE',
    navigation: 'SU PORTAL',
    account: 'Cuenta',
    demoView: 'Vista {name}',
    daughter: 'Hija',
    patient: 'Paciente consultado',
    role: 'Rol',
    shortcuts: 'A un toque',
    resultsShortcut: 'Consulte sus estudios y sus explicaciones.',
    careShortcut: 'Revise su equipo, indicaciones y medicinas.',
    familyShortcut: 'Consulte los accesos del ejemplo para su familia.',
    stage: 'Etapa {stage} de 7 · simulada',
    stages: 'Ver las etapas de la visita',
    visitData: 'Datos de la visita de ejemplo',
    location: 'Ubicación',
    clinician: 'Profesional a cargo',
    cubicle: 'Cubículo {number}',
    doctor: 'Dra. {name}',
    demoTools: 'Opciones de demostración',
    allStagesNote: 'Solo se indica la etapa seleccionada; las demás no se declaran completadas.',
    familyNotice: 'Estos permisos cambian lo que Lourdes Santiago Rivera puede ver en esta demostración. Se conservan al cambiar de vista y se reinician al recargar. No modifican permisos reales.',
    servicesHelp: 'Servicios y ayuda',
  },
  en: {
    resultsAvailable: 'Results available',
    portalTagline: 'Your portal, your health record.',
    demo: 'Demonstration · fictional data',
    resultsIntro: 'Your hospital results, in your hands.',
    searchFilters: 'Search or filter',
    viewReport: 'View report',
    viewReportLabel: 'View report: {name}',
    closeReport: 'Close report',
    closeReportLabel: 'Close report: {name}',
    aboutReport: 'About this example report',
    demoControls: 'Demonstration controls',
    demoControlsBody: 'Switch the example view. This does not sign you in or change real permissions.',
    demoDetails: 'About this demonstration',
    demoBody: 'This prototype is not connected to hospitals or PRHIE. Accounts, permissions and changes are local examples; reloading resets them.',
    welcome: 'Your portal,\nyour health record.',
    welcomeBody: 'Your visit, results and care, in a space designed for you and your family.',
    entryTitle: 'Explore the portal',
    entryBody: 'Choose a demonstration account to get started.',
    patientPortal: 'PATIENT PORTAL',
    navigation: 'YOUR PORTAL',
    account: 'Account',
    demoView: 'View {name}',
    daughter: 'Daughter',
    patient: 'Patient being viewed',
    role: 'Role',
    shortcuts: 'Quick access',
    resultsShortcut: 'View your tests and their explanations.',
    careShortcut: 'Review your team, instructions and medicines.',
    familyShortcut: 'View the example family access.',
    stage: 'Stage {stage} of 7 · simulated',
    stages: 'View the visit stages',
    visitData: 'Example visit details',
    location: 'Location',
    clinician: 'Care professional',
    cubicle: 'Cubicle {number}',
    doctor: 'Dr. {name}',
    demoTools: 'Demonstration options',
    allStagesNote: 'Only the selected stage is indicated; other stages are not marked complete.',
    familyNotice: 'These permissions change what Lourdes Santiago Rivera can view in this demonstration. They persist between views and reset on reload. They do not change real permissions.',
    servicesHelp: 'Services and help',
  },
};

export function uiCopy(language, key, values = {}) {
  return (copy[language]?.[key] ?? copy.en[key] ?? key).replace(/\{(\w+)\}/g, (_, name) => String(values[name] ?? `{${name}}`));
}
