"""Regenerate bundled synthetic PDFs from the CURRENT guarded fixture presentation.
Run using existing ReportLab environment; installs nothing. Never writes public assets.
"""
import base64
import hashlib
import io
import json
from pathlib import Path
import subprocess
from xml.sax.saxutils import escape
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfdoc import PDFInfo, PDFDictionary, PDFString
from reportlab.pdfgen.canvas import Canvas
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, KeepTogether
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.colors import HexColor

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[3]
FONT = Path('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf')
pdfmetrics.registerFont(TTFont('DemoSans', str(FONT)))

class UndatedInfo(PDFInfo):
    def format(self, document):
        return PDFDictionary({key: PDFString(value) for key, value in {
            'Title': 'Synthetic demonstration report', 'Author': '',
            'Subject': 'Fictitious institution; not for medical use',
            'Creator': 'PRPP synthetic PDF generator', 'Producer': 'ReportLab',
        }.items()}).format(document)

class DemoCanvas(Canvas):
    def __init__(self, *args, **kwargs):
        kwargs['invariant'] = 1
        super().__init__(*args, **kwargs)
        self._doc.info = UndatedInfo()

script = """
import {listReports,reportCopy} from './apps/dashboard/src/reports/index.mjs';
const ctx={status:'ready',generation:0,session:{patient:{id:'carmen'},permissions:{estudios:true}}};
console.log(JSON.stringify(['en','es'].map(language=>({language,copy:reportCopy[language],reports:listReports(ctx,language).reports}))));
"""
models = json.loads(subprocess.check_output(['node', '--input-type=module', '-e', script], cwd=ROOT))
styles = {name: ParagraphStyle(name, fontName='DemoSans', fontSize=size, leading=leading, textColor=HexColor(color), spaceAfter=after) for name, size, leading, color, after in [
    ('warning', 10, 15, '#953525', 14), ('title', 22, 29, '#16382d', 10),
    ('institution', 13, 19, '#16382d', 5), ('body', 10, 15, '#253e36', 6),
    ('small', 8, 12, '#51665e', 5), ('item', 13, 18, '#16382d', 8),
]}
def para(text, style='body'):
    return Paragraph(escape(str(text)), styles[style])

def render(report, copy):
    target = io.BytesIO()
    doc = SimpleDocTemplate(target, pagesize=(595.28,841.89), leftMargin=46, rightMargin=46, topMargin=40, bottomMargin=40)
    story = [para(copy['warning'], 'warning'), para(report['title'], 'title'),
             para(report['institution'], 'institution'), para(copy['fictitious'], 'small'),
             para(copy['grouping'], 'small'), para(copy['provisional'], 'small'), Spacer(1,18)]
    for item in report['items']:
        value = str(item['value']) + (' ' + item['unit'] if item['unit'] else '')
        block = [para(item['title'],'item'),para(copy['value'] + ': ' + value),
                 para(copy['range'] + ': ' + (item['range'] or copy['missing'])),
                 para(copy['interpretation'] + ': ' + item['interpretation'] + (f" ({item['interpretationCode']})" if item['interpretationCode'] else '')),
                 para(copy['status'] + ': ' + item['statusLabel']),
                 para(copy['note'] + ': ' + item['note']), Spacer(1,14)]
        story.append(KeepTogether(block))
    doc.build(story, canvasmaker=DemoCanvas)
    return target.getvalue()

assets = {}
manifest = {'font_sha256': hashlib.sha256(FONT.read_bytes()).hexdigest(), 'reports': {}}
for model in models:
    for report in model['reports']:
        key = report['id'] + '-' + model['language']
        data = render(report, model['copy'])
        assert data == render(report, model['copy']), 'PDF generation is not deterministic'
        assets[key] = base64.b64encode(data).decode('ascii')
        manifest['reports'][key] = {'bytes': len(data), 'sha256': hashlib.sha256(data).hexdigest()}
(HERE / 'pdf-assets.mjs').write_text('// Generated by generate.py. SYNTHETIC ONLY. No HTTP PDF endpoint.\nexport const pdfAssets = Object.freeze(' + json.dumps(assets, sort_keys=True, indent=2) + ');\n')
(HERE / 'manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')
print(json.dumps(manifest, indent=2))
