const copy = {
  es: {
    demo: 'Demostración · datos ficticios',
    demoDetails: 'Acerca de esta demostración',
    demoBody: 'Este prototipo no está conectado a hospitales ni a PRHIE. Las cuentas, los permisos y los cambios son ejemplos locales; no se guardan al recargar.',
    welcome: 'Su portal,\na su ritmo.',
    welcomeBody: 'Su visita, sus resultados y su cuidado, en un espacio pensado para usted y su familia.',
    entryTitle: 'Explore el portal',
    entryBody: 'Seleccione una cuenta de demostración para comenzar.',
    patientPortal: 'PORTAL DEL PACIENTE',
    navigation: 'SU PORTAL',
    account: 'Cuenta',
    patient: 'Paciente consultado',
    role: 'Rol',
    shortcuts: 'A un toque',
    resultsShortcut: 'Consulte sus estudios y sus explicaciones.',
    careShortcut: 'Revise su equipo, indicaciones y medicinas.',
    familyShortcut: 'Consulte los accesos del ejemplo para su familia.',
    stage: 'Etapa {stage} de 7 · simulada',
    stages: 'Ver las etapas de la visita',
    visitData: 'Datos de la visita de ejemplo',
    location: 'Ubicación',
    clinician: 'Profesional a cargo',
    cubicle: 'Cubículo {number}',
    doctor: 'Dra. {name}',
    demoTools: 'Opciones de demostración',
    allStagesNote: 'Solo se indica la etapa seleccionada; las demás no se declaran completadas.',
    familyNotice: 'Los cambios de acceso en esta pantalla son una simulación local. No modifican permisos reales.',
    servicesHelp: 'Servicios y ayuda',
  },
  en: {
    demo: 'Demonstration · fictional data',
    demoDetails: 'About this demonstration',
    demoBody: 'This prototype is not connected to hospitals or PRHIE. Accounts, permissions and changes are local examples; reloading resets them.',
    welcome: 'Your portal,\nat your pace.',
    welcomeBody: 'Your visit, results and care, in a space designed for you and your family.',
    entryTitle: 'Explore the portal',
    entryBody: 'Choose a demonstration account to get started.',
    patientPortal: 'PATIENT PORTAL',
    navigation: 'YOUR PORTAL',
    account: 'Account',
    patient: 'Patient being viewed',
    role: 'Role',
    shortcuts: 'Quick access',
    resultsShortcut: 'View your tests and their explanations.',
    careShortcut: 'Review your team, instructions and medicines.',
    familyShortcut: 'View the example family access.',
    stage: 'Stage {stage} of 7 · simulated',
    stages: 'View the visit stages',
    visitData: 'Example visit details',
    location: 'Location',
    clinician: 'Care professional',
    cubicle: 'Cubicle {number}',
    doctor: 'Dr. {name}',
    demoTools: 'Demonstration options',
    allStagesNote: 'Only the selected stage is indicated; other stages are not marked complete.',
    familyNotice: 'Access changes on this screen are a local simulation. They do not change real permissions.',
    servicesHelp: 'Services and help',
  },
};

export function uiCopy(language, key, values = {}) {
  return (copy[language]?.[key] ?? copy.en[key] ?? key).replace(/\{(\w+)\}/g, (_, name) => String(values[name] ?? `{${name}}`));
}
