import test from 'node:test';
import assert from 'node:assert/strict';
import { createDemoStore } from '../src/context.mjs';
import { loadResults } from '../src/results.mjs';
import { downloadReport } from '../src/reports/index.mjs';
const load=async(account,role)=>({account,role,patient:{id:'carmen'},permissions:{visita:true,medicinas:true,instrucciones:true,estudios:role==='self'},client:{clear(){}}});
const settled=async()=>{await new Promise(resolve=>setImmediate(resolve));};
const all={status:true,medicines:true,instructions:true,studies:true};
test('owner grants apply to delegate results/PDF, survive views and are cleared by closing',async()=>{
 const store=createDemoStore(load);await settled();
 assert.equal(typeof store.saveFamilyPermissions,'function');
 const owner=store.getSnapshot().session;
 await store.saveFamilyPermissions({caregiverId:'lourdes',permissions:all},owner);
 await store.enter('lourdes','delegate');
 assert.equal(store.getSnapshot().session.permissions.estudios,true);
 assert.equal((await loadResults(store.getSnapshot().session)).items.length,5);
 let saved=0;
 assert.equal((await downloadReport({getContext:()=>({...store.getSnapshot(),generation:1}),reportId:'a',loadPdf:async()=>new Uint8Array([1]),save:()=>{saved++;}})).status,'downloaded');
 assert.equal(saved,1);
 await store.enter('carmen','self');
 assert.equal(store.getFamilyAccess()[0].permissions.studies,true);
 await store.saveFamilyPermissions({caregiverId:'lourdes',permissions:{...all,studies:false}},store.getSnapshot().session);
 await store.enter('lourdes','delegate');
 let reads=0;
 assert.equal((await loadResults(store.getSnapshot().session,()=>{reads++;return [];})).status,'restricted');
 assert.equal(reads,0);
 assert.equal((await downloadReport({getContext:()=>({...store.getSnapshot(),generation:2}),reportId:'a',loadPdf:async()=>{reads++;}})).status,'restricted');
 assert.equal(reads,0);
 store.close();await store.enter('carmen','self');
 assert.equal(store.getFamilyAccess()[0].permissions.studies,false);
 store.close();
});
test('only current owner can save; malformed maps and stale owner callbacks fail closed',async()=>{
 const store=createDemoStore(load);await settled();const owner=store.getSnapshot().session;
 const save=p=>store.saveFamilyPermissions(p,owner);
 for(const permissions of [{}, {...all,studies:'true'}, {...all,status:false}]) assert.throws(()=>save({caregiverId:'lourdes',permissions}));
 assert.throws(()=>save({caregiverId:'someone-else',permissions:all}));
 const copy=store.getFamilyAccess();copy[0].permissions.studies=true;
 assert.equal(store.getFamilyAccess()[0].permissions.studies,false);
 await store.enter('lourdes','delegate');
 assert.throws(()=>save({caregiverId:'lourdes',permissions:all}));
 assert.throws(()=>store.saveFamilyPermissions({caregiverId:'lourdes',permissions:all},store.getSnapshot().session));
 assert.equal(store.getSnapshot().session.permissions.estudios,false);
 store.close();
});
test('each category maps independently and all-off removes all delegated categories',async()=>{
 const store=createDemoStore(load);await settled();
 store.saveFamilyPermissions({caregiverId:'lourdes',permissions:{...all,medicines:false,instructions:false}},store.getSnapshot().session);
 await store.enter('lourdes','delegate');
 assert.deepEqual(store.getSnapshot().session.permissions,{visita:true,medicinas:false,instrucciones:false,estudios:true});
 await store.enter('carmen','self');
 store.saveFamilyPermissions({caregiverId:'lourdes',permissions:{status:false,medicines:false,instructions:false,studies:false}},store.getSnapshot().session);
 await store.enter('lourdes','delegate');
 assert.deepEqual(store.getSnapshot().session.permissions,{visita:false,medicinas:false,instrucciones:false,estudios:false});
 const fresh=createDemoStore(load);await settled();assert.equal(fresh.getFamilyAccess()[0].permissions.status,true);
 store.close();fresh.close();
});
